# Windows PowerShell Script to enable Google Chrome AI features (GLIC)
# Auto-generated by Antigravity

$ErrorActionPreference = "Stop"

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "         正在启用 Google Chrome AI (GLIC)        " -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

$localStatePath = "$env:LOCALAPPDATA\Google\Chrome\User Data\Local State"

# 1. Check if Chrome Local State exists
if (-not (Test-Path $localStatePath)) {
    Write-Host "[错误] 找不到 Chrome Local State 配置文件。" -ForegroundColor Red
    Write-Host "请确认这台电脑上是否安装了 Google Chrome 浏览器。" -ForegroundColor Red
    Write-Host ""
    Read-Host "按回车键退出..."
    exit
}

# 2. Kill Chrome process
Write-Host "[1/5] 正在关闭所有 Chrome 浏览器进程..." -ForegroundColor Yellow
$chromeProcesses = Get-Process -Name chrome -ErrorAction SilentlyContinue
if ($chromeProcesses) {
    Stop-Process -Name chrome -Force
    Start-Sleep -Seconds 2
    Write-Host "[SUCCESS] 已成功关闭 Chrome 浏览器进程。" -ForegroundColor Green
} else {
    Write-Host "[INFO] 未检测到正在运行的 Chrome 浏览器。" -ForegroundColor Gray
}

# 3. Create Backup
$timestamp = Get-Date -Format "yyyyMMddHHmmss"
$backupPath = "$localStatePath.backup.$timestamp"
try {
    Copy-Item -Path $localStatePath -Destination $backupPath -Force
    Write-Host "[2/5] 已成功创建原配置文件的备份：" -ForegroundColor Green
    Write-Host "      $backupPath" -ForegroundColor Gray
} catch {
    Write-Host "[错误] 备份配置文件失败：$_" -ForegroundColor Red
    Read-Host "按回车键退出..."
    exit
}

# 4. Modify JSON
Write-Host "[3/5] 正在读取并修改配置文件..." -ForegroundColor Yellow
try {
    $jsonText = Get-Content -Path $localStatePath -Raw -Encoding Utf8
    $json = ConvertFrom-Json $jsonText
    
    # Update variations
    $json.variations_country = "us"
    $json.variations_permanent_consistency_country = @("1", "us")
    
    # Update is_glic_eligible
    $modifiedProfilesCount = 0
    if ($json.profile -and $json.profile.info_cache) {
        $profiles = $json.profile.info_cache | Get-Member -MemberType NoteProperty
        foreach ($p in $profiles) {
            $pName = $p.Name
            $profileObj = $json.profile.info_cache.$pName
            if ($profileObj.is_glic_eligible -eq $null) {
                $profileObj | Add-Member -NotePropertyName "is_glic_eligible" -NotePropertyValue $true -Force
            } else {
                $profileObj.is_glic_eligible = $true
            }
            $modifiedProfilesCount++
            Write-Host "      已为配置文件 [$pName] 启用 GLIC AI 资格" -ForegroundColor Gray
        }
    }
    
    Write-Host "[4/5] 正在保存修改..." -ForegroundColor Yellow
    # Convert back to JSON
    $newJsonText = $json | ConvertTo-Json -Depth 100
    
    # Write using UTF-8 without BOM to match Chrome's native encoding
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [IO.File]::WriteAllText($localStatePath, $newJsonText, $utf8NoBom)
    
    Write-Host "[5/5] [SUCCESS] 配置修改完成！" -ForegroundColor Green
    Write-Host ""
    Write-Host "==================================================" -ForegroundColor Green
    Write-Host " 恭喜！Chrome AI 功能（GLIC）已成功激活。" -ForegroundColor Green
    Write-Host " 现在您可以重新打开 Chrome 浏览器进行体验了。" -ForegroundColor Green
    Write-Host "==================================================" -ForegroundColor Green
    Write-Host ""
} catch {
    Write-Host "[错误] 修改或保存配置文件时出错：$_" -ForegroundColor Red
}

Read-Host "按回车键`/Enter`键退出..."
